### ISSUE TITLE
Library loading needs to be included in code chunks

### ISSUE THREAD

**Issue by bhuvad** [DavisLaboratory/SingscoreAMLMutations#4]
Libraries load well when running the entire workflow, however, when copying and pasting chunks of code, some libraries are missing and return errors. This is especially a problem when delivering workshops. We need to load libraries in the relevant chunks as well as in the first chunk (to avoid loading messages).

**Comment by Malvikakh** [comment]
The issue has been solved in commit [3efc582](https://github.com/DavisLaboratory/SingscoreAMLMutations/commit/3efc582145d1a069fc2b5abff30897eef32dd56b)
